rust:
  repo: https://github.com/breez/breez-sdk-liquid
  rev: 96a9815bf8e744f8d4c9108741078a48ebd2a596
  manifestPath: lib/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
android:
  useSharedLibrary: true
ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/RnBreezSdkLiquid
turboModule:
  cpp: cpp
  ts: src
noOverwrite:
  - "android/src/main/AndroidManifest.xml"
