rust:
  repo: https://github.com/breez/breez-sdk-liquid
  rev: b97620683c00bc49470fb726debaf1af365616be
  manifestPath: lib/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
android:
  useSharedLibrary: true
ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/RnBreezSdkLiquid
turboModule:
  cpp: cpp
  ts: src
noOverwrite:
  - "android/src/main/AndroidManifest.xml"
