rust:
  repo: https://github.com/breez/breez-sdk-liquid
  rev: 444f3821b2d696a2e448c3c56cf60d833e7b5ae6
  manifestPath: lib/bindings/Cargo.toml
bindings:
  cpp: cpp/generated
  ts: src/generated
android:
  useSharedLibrary: true
ios:
  targets:
    - aarch64-apple-ios
    - aarch64-apple-ios-sim
    - x86_64-apple-ios
  frameworkName: build/RnBreezSdkLiquid
turboModule:
  cpp: cpp
  ts: src
noOverwrite:
  - "android/src/main/AndroidManifest.xml"
